@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Purchaserequisition item'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity zI_Purchaserequisitionitem as select from I_PurchaseRequisitionItemAPI01
{
    key PurchaseRequisition,
    key PurchaseRequisitionItem,
    PurchaseReqnItemUniqueID,
    PurchasingDocument,
    PurchasingDocumentItem,
    PurReqnReleaseStatus,
    PurchaseRequisitionType,
    PurchasingDocumentSubtype,
    PurchasingDocumentItemCategory,
    PurchaseRequisitionItemText,
    AccountAssignmentCategory,
    Material,
    MaterialGroup,
    PurchasingDocumentCategory,
     @Semantics.quantity.unitOfMeasure: 'BaseUnit'
    RequestedQuantity,
    BaseUnit,
    @Semantics.amount.currencyCode: 'PurReqnItemCurrency'
    PurchaseRequisitionPrice,
    PurReqnPriceQuantity,

    MaterialGoodsReceiptDuration,
    ReleaseCode,
    PurchaseRequisitionReleaseDate,
    PurchasingOrganization,
    PurchasingGroup,
    Plant,
    SourceOfSupplyIsAssigned,
    SupplyingPlant,
       @Semantics.quantity.unitOfMeasure: 'BaseUnit'
    OrderedQuantity,
    @Semantics.amount.currencyCode: 'PurReqnItemCurrency'
    PurReqnLimitConsumptionAmt,
    DeliveryDate,
    CreationDate,
    PurchaseReqnCreationDate,
    CreationTime,
    ProcessingStatus,
    PurchasingInfoRecord,
    Supplier,
    IsDeleted,
    FixedSupplier,
    RequisitionerName,
    CreatedByUser,
    PurReqCreationDate,
    DeliveryAddressID,
    ManualDeliveryAddressID,
    PurReqnItemCurrency,
    MaterialPlannedDeliveryDurn,
    DelivDateCategory,
    MultipleAcctAssgmtDistribution,
    StorageLocation,
    PurReqnSSPRequestor,
    PurReqnSSPAuthor,
    PurchaseContract,
    PurReqnSourceOfSupplyType,
    PurchaseContractItem,
    ConsumptionPosting,
    PurReqnOrigin,
    PurReqnSSPCatalog,
    PurReqnSSPCatalogItem,
    PurReqnSSPCrossCatalogItem,
    IsPurReqnBlocked,
    ItemDeliveryAddressID,
    Language,
    IsClosed,
    Reservation,
    ReleaseIsNotCompleted,
    ServicePerformer,
    ProductType,
    PurchaseRequisitionStatus,
    ReleaseStrategy,
    PerformancePeriodStartDate,
    PerformancePeriodEndDate,
    CompanyCode,
    SupplierMaterialNumber,
    Batch,
    MaterialRevisionLevel,
    MaterialRevisionLevel_2,
    MinRemainingShelfLife,
    @Semantics.amount.currencyCode: 'PurReqnItemCurrency'
    ItemNetAmount,
    GoodsReceiptIsExpected,
    InvoiceIsExpected,
    GoodsReceiptIsNonValuated,
    RequirementTracking,
    MRPArea,
    MRPController,
    TaxCode,
    PurchaseRequisitionIsFixed,
    AddressID,
    LastChangeDateTime,
     @Semantics.amount.currencyCode: 'PurReqnItemCurrency'
    ExpectedOverallLimitAmount,
    @Semantics.amount.currencyCode: 'PurReqnItemCurrency'
    OverallLimitAmount,
    PurContractForOverallLimit,
    PurContractItemForOverallLimit,
    ProcurementHubSourceSystem,
    ExtPurgOrgForPurg,
    ExtCompanyCodeForPurg,
    ExtPlantForPurg,
    ExtInfoRecordForPurg,
    ExtContractItemForPurg,
    ExtContractForPurg,
    ExtDesiredSupplierForPurg,
    ExtFixedSupplierForPurg,
    ExtMaterialForPurg,
    IsOutline,
    PurchasingParentItem,
    PurgConfigurableItemNumber,
    PurgExternalSortNumber,
    IsPurReqnCmplt,
    PurReqnItemBlockingReasonText,
    InventorySpecialStockType,
    QuotaArrangement,
    QuotaArrangementItem,
    /* Associations */
    _PurchaseRequisition,
    _PurReqnAcctAssgmt
}
